[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "TranceSQL"
version = "0.1.0"
authors = [
    { name="Navakanth Reddy Dumpa", email="navakanth@example.com" }
]
description = "A self-correcting natural language to SQL translator using Gemini 2.5 Pro"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Database",
    "Topic :: Scientific/Engineering :: Artificial Intelligence"
]
dependencies = [
    "google-genai>=2.0.0",
    "python-dotenv>=1.0.0"
]

[project.urls]
"Homepage" = "https://github.com/navakanth1984/TranceSQL"
"Bug Tracker" = "https://github.com/navakanth1984/TranceSQL/issues"
